"""Write the paper's result tables from the committed adjudication records, so no number
in them is typed by hand:

- paper/sections/full_protocol_table.tex: submitted vs full-protocol verdicts (v1);
- paper/sections/groundwater_results.tex: G-1..G-5 for each model set that has a record;
- paper/sections/v2_table.tex: v2 re-test verdicts, if results/adjudication_v2.json exists.
"""
from __future__ import annotations

import json

from report.common import REPO_ROOT

RESULTS = REPO_ROOT / "results"
SECTIONS = REPO_ROOT / "paper" / "sections"


def _load(name):
    path = RESULTS / name
    return json.loads(path.read_text(encoding="utf-8")) if path.is_file() else None


def _v(verdict: str | None) -> str:
    if verdict is None:
        return "---"
    text = verdict.replace("_", " ").title()
    return f"\\textbf{{{text}}}" if verdict == "CONFIRMED" else text


def _tex(s: str) -> str:
    return s.replace("_", "\\_")


def full_protocol_table() -> None:
    sub, full = _load("adjudication.json"), _load("adjudication_v1_full.json")
    rows = []
    for check in sub:
        rows.append(f"  {_tex(check)} & {_v(sub[check].get('verdict'))} & {_v(full.get(check, {}).get('verdict'))} \\\\")
    n_sub = sum(v.get("verdict") == "CONFIRMED" for v in sub.values())
    n_full = sum(v.get("verdict") == "CONFIRMED" for v in full.values())
    body = "\n".join(rows)
    (SECTIONS / "full_protocol_table.tex").write_text(
        "% Generated by scripts/report/paper_tables.py from results/adjudication*.json.\n"
        "\\begin{table}[htbp]\n  \\centering\n  \\small\n"
        "  \\begin{tabular}{lll}\n  \\toprule\n"
        "  Check & Submitted (2 seeds) & Full protocol (5 seeds) \\\\\n  \\midrule\n"
        f"{body}\n  \\midrule\n"
        f"  Confirmed & {n_sub} of {len(sub)} & {n_full} of {len(full)} \\\\\n"
        "  \\bottomrule\n  \\end{tabular}\n"
        "  \\caption{Every pre-registered check at submission and at the completed protocol,\n"
        "    adjudicated by the same unchanged script.}\n"
        "  \\label{tab:fullprotocol}\n\\end{table}\n",
        encoding="utf-8", newline="\n",
    )


def _gw_rows(rec: dict, q: str) -> list[str]:
    fam = rec.get("families", {})
    desc = {
        "G-1": f"median rel-$L^2$ {fam.get(q, {}).get('median_rel_l2', float('nan')):.4f} (need $\\le 0.01$)",
        "G-2": f"ratio {rec.get('G-2', {}).get('measured_ratio', float('nan')):.2f}$\\times$ (need $\\ge1.3$)",
        "G-3": f"ratio {rec.get('G-3', {}).get('measured_ratio', float('nan')):.2f}$\\times$ (need $\\ge1.5$)",
        "G-4": f"{100 * rec.get('G-4', {}).get('overlap_fraction', float('nan')):.1f}\\% inside $\\Omega$ (need $\\ge70$\\%)",
        "G-5": f"{rec.get('G-5', {}).get('median_waterlogged_m', float('nan')):.0f}\\,m vs exact "
               f"{rec.get('exact_waterlogged_m', float('nan')):.0f}\\,m (need within 5\\%)",
    }
    return [f"  {g} & {_v(rec.get(g, {}).get('verdict'))} & {desc[g]} \\\\" for g in desc]


def groundwater_results() -> None:
    parts = ["% Generated by scripts/report/paper_tables.py from results/adjudication_groundwater_*.json."]
    for name, q, label in (("v1", "q_serial", "v1 models"), ("v2", "q_serial_v2", "v2 models")):
        rec = _load(f"adjudication_groundwater_{name}.json")
        if not rec or "families" not in rec:
            continue
        fam_rows = "\n".join(
            f"  \\texttt{{{_tex(f)}}} & {v['median_rel_l2']:.4f} & {v['median_waterlogged_m']:.0f} & {v['n']} \\\\"
            for f, v in sorted(rec["families"].items())
        )
        parts.append(
            "\\begin{table}[htbp]\n  \\centering\n  \\small\n  \\begin{tabular}{lll}\n  \\toprule\n"
            "  Claim & Verdict & Measured \\\\\n  \\midrule\n" + "\n".join(_gw_rows(rec, q)) +
            f"\n  \\bottomrule\n  \\end{{tabular}}\\\\[6pt]\n"
            f"  \\begin{{tabular}}{{lrrr}}\n  \\toprule\n"
            f"  Model & median rel-$L^2$ & median waterlogged (m) & seeds \\\\\n  \\midrule\n{fam_rows}\n"
            f"  \\bottomrule\n  \\end{{tabular}}\n"
            f"  \\caption{{Groundwater predictions, {label}, seeds 10--14. Exact waterlogged length:"
            f" {rec['exact_waterlogged_m']:.0f}\\,m.}}\n  \\label{{tab:gw{name}}}\n\\end{{table}}\n"
        )
    (SECTIONS / "groundwater_tables.tex").write_text("\n".join(parts) + "\n", encoding="utf-8", newline="\n")


# The claims re-tested in this round (design spec, amendment 5).
V2_RETESTED = ("PR-1", "PR-2", "PR-3", "PR-6 (poisson)", "PR-7 (poisson)", "PR-8 (poisson)", "PR-11", "PR-12")


def v2_table() -> None:
    rec = _load("adjudication_v2.json")
    if not rec:
        return
    rows = []
    for check, v in rec.items():
        if check not in V2_RETESTED:
            continue
        ratio = v.get("measured_ratio")
        if isinstance(ratio, (int, float)):
            extra = f"{ratio:.2f}$\\times$"
        elif isinstance(v.get("measured_gap"), (int, float)):
            extra = f"gap {v['measured_gap']:.1f}"
        elif isinstance(v.get("overlap_fraction"), (int, float)):
            extra = f"{100 * v['overlap_fraction']:.1f}\\% in $\\Omega$"
        elif isinstance(v.get("median_frobenius"), (int, float)):
            extra = f"drift {v['median_frobenius']:.2f}"
        else:
            extra = ""
        rid = check.replace("PR-", "R-")
        rows.append(f"  {_tex(rid)} & {_v(v.get('verdict'))} & {extra} \\\\")
    (SECTIONS / "v2_table.tex").write_text(
        "% Generated by scripts/report/paper_tables.py from results/adjudication_v2.json.\n"
        "\\begin{table}[htbp]\n  \\centering\n  \\small\n  \\begin{tabular}{llr}\n  \\toprule\n"
        "  Claim & Verdict & Measured \\\\\n  \\midrule\n" + "\n".join(rows) +
        "\n  \\bottomrule\n  \\end{tabular}\n"
        "  \\caption{v1's claims re-tested on the v2 model, seeds 10--14 (Poisson). Ratios as each\n"
        "    claim defines them: R-1, R-2 and R-6 give baseline error over v2 error (above 1: v2 better);\n"
        "    R-3 gives v2 error over \\texttt{c\\_rff\\_matched\\_v2} error (3.3: v2 worse). Claims on other\n"
        "    problems were not run in this round.}\n  \\label{tab:v2}\n\\end{table}\n",
        encoding="utf-8", newline="\n",
    )


if __name__ == "__main__":
    full_protocol_table()
    groundwater_results()
    v2_table()
