"""Write the paper's result tables from the committed adjudication records, so no number
in them is typed by hand. Claims are labelled in plain words; the pre-registered wording
of each is in docs/predictions*.md.

- paper/sections/claims_table.tex: the one-copy circuit's claims across the six problems;
- paper/sections/ensemble_table.tex: the eight-copy circuit's claims on Poisson;
- paper/sections/groundwater_tables.tex: the groundwater claims and every model's error.
"""
from __future__ import annotations

import json

from report.common import REPO_ROOT

RESULTS = REPO_ROOT / "results"
SECTIONS = REPO_ROOT / "paper" / "sections"
NAN = float("nan")

# Adjudication key -> plain-language claim (docs/predictions.md, same order).
CLAIMS = {
    "PR-1": "Beats the large MLP on Poisson ($\\ge2\\times$)",
    "PR-2": "Beats Fourier features on Poisson ($\\ge1.3\\times$)",
    "PR-3": "Matches the frequency-matched classical model on Poisson (within $1.3\\times$)",
    "PR-4": "Heat: no model beats the MLP by more than 5\\%",
    "PR-5": "Helmholtz: the gain over the MLP grows with $k$",
    "PR-6 (poisson)": "Designed beats random frequencies, Poisson ($\\ge1.5\\times$)",
    "PR-6 (heat)": "Designed beats random frequencies, heat ($\\ge1.5\\times$)",
    "PR-7 (poisson)": "NTK flatter inside $\\Omega$ than outside, Poisson",
    "PR-7 (helmholtz_k10)": "NTK flatter inside $\\Omega$ than outside, Helmholtz $k{=}10$",
    "PR-8 (poisson)": "Gain over the MLP lies inside $\\Omega$, Poisson ($\\ge70\\%$)",
    "PR-8 (helmholtz_k10)": "Gain over the MLP lies inside $\\Omega$, Helmholtz $k{=}10$",
    "PR-9": "Higher coverage gives lower error ($\\rho\\le-0.7$)",
    "PR-10": "Gradient variance stays above the barren-plateau line",
    "PR-11": "Leaves the lazy-training regime earlier than classical models",
    "PR-12": "Encoder drift stays below 0.2, so $\\Omega$ stays valid",
}
GROUNDWATER = {
    "G-1": "Error below 1\\%",
    "G-2": "Beats a classical network of the same size ($\\ge1.3\\times$)",
    "G-3": "Beats the same circuit with random frequencies ($\\ge1.5\\times$)",
    "G-4": "Gain over the MLP lies inside $\\Omega$ ($\\ge70\\%$)",
    "G-5": "Waterlogged length within 5\\% of the exact 713\\,m",
}
MODEL_NAMES = {
    "q_serial": "SMCD circuit, 1 copy", "q_serial_v2": "SMCD circuit, 8 copies",
    "q_random": "random frequencies, 1 copy", "q_random_v2": "random frequencies, 8 copies",
    "c_mlp": "MLP, large", "c_mlp_matched": "MLP, size of 1 copy", "c_mlp_matched_v2": "MLP, size of 8 copies",
    "c_rff_matched": "frequency-matched, size of 1 copy", "c_rff_matched_v2": "frequency-matched, size of 8 copies",
}
# Claims tested on the eight-copy circuit (docs/predictions_v2.md).
ENSEMBLE_CLAIMS = ("PR-1", "PR-2", "PR-3", "PR-6 (poisson)", "PR-7 (poisson)", "PR-8 (poisson)", "PR-11", "PR-12")


def _load(name):
    path = RESULTS / name
    return json.loads(path.read_text(encoding="utf-8")) if path.is_file() else None


def _v(verdict: str | None) -> str:
    if verdict is None:
        return "---"
    text = verdict.replace("_", " ").capitalize()
    return f"\\textbf{{{text}}}" if verdict == "CONFIRMED" else text


def _measured(v: dict) -> str:
    if isinstance(v.get("measured_ratio"), (int, float)):
        return f"{v['measured_ratio']:.2f}$\\times$"
    if isinstance(v.get("measured_gap"), (int, float)):
        return f"gap {v['measured_gap']:.1f}"
    if isinstance(v.get("overlap_fraction"), (int, float)):
        return f"{100 * v['overlap_fraction']:.1f}\\%"
    if isinstance(v.get("median_frobenius"), (int, float)):
        return f"{v['median_frobenius']:.2f}"
    if isinstance(v.get("slope_b"), (int, float)):
        return f"slope {v['slope_b']:.2f}, $R^2$ {v['fit_r2']:.3f}"
    if isinstance(v.get("median_hybrid_drift"), (int, float)):
        return f"{v['median_hybrid_drift']:.2f} vs {v['median_classical_drift']:.1e}"
    return ""


def _write(name: str, source: str, body: str) -> None:
    (SECTIONS / name).write_text(f"% Generated by scripts/report/paper_tables.py from {source}.\n{body}",
                                 encoding="utf-8", newline="\n")


def _claims_table(rec: dict, keys, caption: str, label: str) -> str:
    rows = "\n".join(f"  {CLAIMS[k]} & {_v(rec[k].get('verdict'))} & {_measured(rec[k])} \\\\"
                     for k in keys if k in rec)
    n_conf = sum(rec[k].get("verdict") == "CONFIRMED" for k in keys if k in rec)
    n = sum(k in rec for k in keys)
    return ("\\begin{table}[htbp]\n  \\centering\n  \\small\n  \\begin{tabular}{p{0.5\\linewidth}lr}\n  \\toprule\n"
            "  Claim & Verdict & Measured \\\\\n  \\midrule\n" + rows +
            f"\n  \\midrule\n  Confirmed & {n_conf} of {n} & \\\\\n  \\bottomrule\n  \\end{{tabular}}\n"
            f"  \\caption{{{caption}}}\n  \\label{{{label}}}\n\\end{{table}}\n")


def claims_table() -> None:
    rec = _load("adjudication_v1_full.json")
    if not rec:
        return
    _write("claims_table.tex", "results/adjudication_v1_full.json", _claims_table(
        rec, list(CLAIMS),
        "Pre-registered claims about the one-copy SMCD circuit, seeds 0--4, as the adjudication\n"
        "    script scores them. Ratios are baseline error over circuit error, except the\n"
        "    frequency-matched comparison (circuit over baseline) and drift (hybrid vs classical).",
        "tab:claims"))


def ensemble_table() -> None:
    rec = _load("adjudication_v2.json")
    if not rec:
        return
    _write("ensemble_table.tex", "results/adjudication_v2.json", _claims_table(
        rec, ENSEMBLE_CLAIMS,
        "Pre-registered claims about the eight-copy SMCD circuit on Poisson, held-out seeds\n"
        "    10--14. The baselines are sized to the eight-copy circuit where the claim names one.",
        "tab:ensemble"))


def groundwater_tables() -> None:
    one, eight = _load("adjudication_groundwater_v1.json"), _load("adjudication_groundwater_v2.json")
    if not one or not eight:
        return

    def cell(rec, g):
        v = rec.get(g, {})
        fam = rec["families"]
        q = "q_serial_v2" if "q_serial_v2" in fam else "q_serial"
        detail = {
            "G-1": f"{100 * fam[q]['median_rel_l2']:.2f}\\%",
            "G-2": f"{v.get('measured_ratio', NAN):.2f}$\\times$",
            "G-3": f"{v.get('measured_ratio', NAN):.2f}$\\times$",
            "G-4": f"{100 * v.get('overlap_fraction', NAN):.1f}\\%",
            "G-5": f"{v.get('median_waterlogged_m', NAN):.0f}\\,m",
        }[g]
        return f"{_v(v.get('verdict'))} ({detail})"

    claims = "\n".join(f"  {GROUNDWATER[g]} & {cell(one, g)} & {cell(eight, g)} \\\\" for g in GROUNDWATER)
    n1 = sum(one[g].get("verdict") == "CONFIRMED" for g in GROUNDWATER)
    n8 = sum(eight[g].get("verdict") == "CONFIRMED" for g in GROUNDWATER)
    models = {**one["families"], **eight["families"]}
    order = ["q_serial_v2", "q_random_v2", "c_mlp_matched_v2", "c_rff_matched_v2", "c_mlp",
             "q_serial", "q_random", "c_mlp_matched", "c_rff_matched"]
    size = {"q_serial_v2": 91, "q_random_v2": 91, "c_mlp_matched_v2": 91, "c_rff_matched_v2": 83,
            "c_mlp": 8513, "q_serial": 14, "q_random": 14, "c_mlp_matched": 13, "c_rff_matched": 13}
    rows = "\n".join(
        f"  {MODEL_NAMES[f]} & {size[f]:,} & {100 * models[f]['median_rel_l2']:.2f}\\% & ".replace("8,5", "8{,}5") +
        f"{models[f]['median_waterlogged_m']:.0f} \\\\"
        for f in order if f in models)
    body = (
        "\\begin{table}[htbp]\n  \\centering\n  \\small\n  \\begin{tabular}{lll}\n  \\toprule\n"
        "  Claim & 1 copy & 8 copies \\\\\n  \\midrule\n" + claims +
        f"\n  \\midrule\n  Confirmed & {n1} of 5 & {n8} of 5 \\\\\n  \\bottomrule\n  \\end{{tabular}}\\\\[8pt]\n"
        "  \\begin{tabular}{lrrr}\n  \\toprule\n"
        "  Model & parameters & median error & waterlogged (m) \\\\\n  \\midrule\n" + rows +
        "\n  \\bottomrule\n  \\end{tabular}\n"
        f"  \\caption{{Groundwater: pre-registered claims for the SMCD circuit with one and eight copies\n"
        f"    (top) and every model's median relative $L^2$ error and waterlogged length (bottom), held-out\n"
        f"    seeds 10--14. Exact waterlogged length: {eight['exact_waterlogged_m']:.0f}\\,m.}}\n"
        "  \\label{tab:gw}\n\\end{table}\n")
    _write("groundwater_tables.tex", "results/adjudication_groundwater_*.json", body)


if __name__ == "__main__":
    claims_table()
    ensemble_table()
    groundwater_tables()
