"""Write paper/wiser_report/numbers.tex: every number the WISER report quotes, as LaTeX
macros read from the committed records, so no figure in the text is typed by hand."""
from __future__ import annotations

import json
import statistics

from report.common import REPO_ROOT, core_runs, select
from report.fig_headline import staircase_steps

OUT = REPO_ROOT / "paper" / "wiser_report" / "numbers.tex"


def _load(name):
    path = REPO_ROOT / "results" / name
    return json.loads(path.read_text(encoding="utf-8")) if path.is_file() else {}


def _confirmed(rec: dict) -> int:
    return sum(isinstance(v, dict) and v.get("verdict") == "CONFIRMED" for v in rec.values())


def main() -> None:
    sub, full = _load("adjudication.json"), _load("adjudication_v1_full.json")
    val = json.loads((REPO_ROOT / "results" / "report" / "validation.json").read_text(encoding="utf-8"))
    gw = json.loads((REPO_ROOT / "results" / "report" / "groundwater_scenarios.json").read_text(encoding="utf-8"))
    gw1, gw2, v2 = _load("adjudication_groundwater_v1.json"), _load("adjudication_groundwater_v2.json"), _load(
        "adjudication_v2.json")
    runs = core_runs()

    def med(problem, family):
        return statistics.median(r.metrics["rel_l2"] for r in select(runs, problem=problem, family=family))

    heat_ratio = med("heat", "q_random") / med("heat", "q_serial")
    leak = max(v["worst_outside_relative"] for v in val["circuit_spectrum"].values())
    boot = val["bootstrap"]["PR-6 heat"]["ci95"]
    lining = gw["canal_lining"]
    wet10 = lining["waterlogged_m"][lining["seepage_cut"].index(min(lining["seepage_cut"], key=lambda c: abs(c - 0.1)))]
    soil = gw["soil_type"]

    stair = staircase_steps()
    n = {
        "StairPi": max(stair["pi"]),
        "StairFastLo": f"{min(stair['15pi']):,}",
        "StairFastHi": f"{max(stair['15pi']):,}",
        "NChecks": len(sub),
        "NConfSub": _confirmed(sub),
        "NConfFull": _confirmed(full),
        "NRuns": len(runs),
        "HeatRatio": f"{heat_ratio:.1f}",
        "HeatCILo": f"{boot[0]:.1f}",
        "HeatCIHi": f"{boot[1]:.1f}",
        "PREightOverlap": f"{100 * full.get('PR-8 (poisson)', {}).get('overlap_fraction', float('nan')):.1f}",
        "Leak": f"{leak:.0e}".replace("e-", "\\times10^{-") + "}",
        "QSerialPoisson": f"{med('poisson', 'q_serial'):.2f}",
        "CMLPPoisson": f"{med('poisson', 'c_mlp'):.2f}",
        "CFFPoisson": f"{med('poisson', 'c_ff'):.2f}",
        "CRFFPoisson": f"{med('poisson', 'c_rff_matched'):.2f}",
        "GWWet": f"{gw['base']['waterlogged_m']:.0f}",
        "GWPeak": f"{gw['base']['peak_m']:.2f}",
        "GWDryCut": f"{100 * lining['first_dry_cut']:.0f}" if lining["first_dry_cut"] is not None else "---",
        "GWWetTen": f"{wet10:.0f}",
        "GWClay": f"{soil['clay loam']['waterlogged_m']:.0f}",
        "PRTenSlope": f"{full.get('PR-10', {}).get('slope_b', float('nan')):.2f}",
        "PRTenRsq": f"{full.get('PR-10', {}).get('fit_r2', float('nan')):.3f}",
        "GWVOneConf": _confirmed({k: v for k, v in gw1.items() if k.startswith("G-")}) if gw1 else "---",
        "GWVTwoConf": _confirmed({k: v for k, v in gw2.items() if k.startswith("G-")}) if gw2 else "---",
        "VTwoConf": _confirmed({k: v for k, v in v2.items() if k in {
            "PR-1", "PR-2", "PR-3", "PR-6 (poisson)", "PR-7 (poisson)", "PR-8 (poisson)", "PR-11", "PR-12"}})
        if v2 else "---",
    }
    lines = ["% Generated by scripts/report/report_numbers.py -- do not edit by hand."]
    lines += [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in n.items()]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
